### ISSUE TITLE
Add sunrise/sunset to each day's entry?

### ISSUE THREAD

**Issue by philgyford** [philgyford/pepysdiary#124]
https://www.timeanddate.com/sun/uk/london?month=9&year=1662

**Comment by hugovk** [comment]
I've knocked up a quick Python script to calculate dawn, dusk, noon, sunrise and sunset times using Astral for the years 1660-1669, and save as JSON, but I'm not entirely sure if we need to add/subtract 11 days to adjust for the calendar. Do you have any "known" sunrise/sunset times to verify?

Here's the sun times, and I can upload the Python script too somewhere if that'd be handy.

For example:
```json
   "1660-01-01": {
        "dawn": "1660-01-01T07:26:14-00:01",
        "dusk": "1660-01-01T16:41:32-00:01",
        "noon": "1660-01-01T12:03:48-00:01",
        "sunrise": "1660-01-01T08:06:11-00:01",
        "sunset": "1660-01-01T16:01:35-00:01"
    },
```


[suntimes.zip](https://github.com/philgyford/pepysdiary/files/296453/suntimes.zip)

**Comment by philgyford** [comment]
Thanks! I get very confused by the dates. I *think* that the dates would be fine as 1660s were in the Gregorian calendar (introduced 1582)... or have I missed something?

Is there a reason these are all `-00:01`?

**Comment by hugovk** [comment]
Query about 11 days (should have been "10 days") comes from this: http://www.pepysdiary.com/diary/1662/05/26/#c31767

And not entirely sure about that `-00:01`:

The JSON is printed as `datetime.datetime` objects in `isoformat()` and `-00:01` is the timezone offset. 

`pprint`ing gives:

`'sunrise': datetime.datetime(1660, 1, 1, 8, 6, 11, tzinfo=<DstTzInfo 'Europe/London' LMT-1 day, 23:59:00 STD>),`

So that says [local mean time](https://www.timeanddate.com/time/local-mean-time.html) minus a day, but plus 23 hours and 59 seconds; i.e. minus a minute.

Here's the code: https://github.com/hugovk/time-tools/blob/master/suntimes.py

**Comment by philgyford** [comment]
I've no time to think about it now, but one data point that might help is Pepys saying 11 June 1663 was "the longest day of the year": http://www.pepysdiary.com/diary/1663/06/11/

**Comment by hugovk** [comment]
Thanks, that's helpful.

The calculated values have this for 11 June 1663:

Sunrise: 1663-06-11 03:41:20-00:01
Sunset:  1663-06-11 20:15:25-00:01
Length of day:  16:34:05

Whereas the calculated values have the longest day on 21 June 1663:

Sunrise: 1663-06-21 03:41:02-00:01
Sunset:  1663-06-21 20:19:55-00:01
Length of day:  16:38:53

And [Dirk in the comments explains](http://www.pepysdiary.com/diary/1663/06/11/#c52049):

> "this is the longest day in the year"

> This has been explained before, but just in case there is still some confusion: **11 June according to the British (uncorrected) calendar** is equivalent to **21 June on the continent, where they were already using the corrected, Gregorian calendar**. The only reason the British had so far refused to make the correction, was that they found it impossible to accept a calendar correction that had been decreed by the Pope in Rome -- but everybody with some learning (including Sam) was aware of the error.
[See also the background info.]

So the JSON values are using the corrected, Gregorian calendar, and not the British (uncorrected) calendar Pepys was using.

So either, when this is implemented, subtract 10 days from the JSON dates to get Pepys' dates.

Or if you prefer, I can redo the JSON to use Pepys' dates.

---

Incidentally [timeanddate.com](https://www.timeanddate.com/sun/uk/london?month=6&year=1663) has the longest day on 11 June 1663 and says:

> \* All times are local mean solar time for London (UTC -0:01:15 hours). Dates are based on the Julian calendar. For years before 1700, the calculated times might be off by many minutes.

> June Solstice (Summer Solstice) is on Thursday, 11 June 1663, 15:27 in London.

**Comment by philgyford** [comment]
Thanks - probably as simple for me to adjust the dates when I import them. I'll try and get on to it before too long.

**Comment by philgyford** [comment]
Very belated thanks again for this - I've finally got the times up on the website!

**Comment by hugovk** [comment]
You're welcome! 

Nice example on https://www.pepysdiary.com/diary/1664/05/13/

> **Times**
> * 3:54 am sunrise
> * 7:56 pm sunset
>
> Up before three o’clock, and a little after upon the water, it being very light as at noon, and a bright sunrising; but by and by a rainbow appeared, the first that ever in a morning I saw, and then it fell a-raining a little, but held up again, and I to [Woolwich](http://www.pepysdiary.com/encyclopedia/1675/),



Thanks again for your excellent Pepys project!
