### ISSUE TITLE
Fix breadcrumbs 'Missing field "id"' issue in Google Search Console

### ISSUE THREAD

**Issue by philgyford** [philgyford/pepysdiary#167]
If Google ever explain what it means.

https://support.google.com/webmasters/thread/15022229?msgid=16544629

**Comment by kaal12** [comment]
We are face the same problem on my site and don't know how to solve this issue. I already read many articles but don't find out this problem on my site: https://www.wishhow.com/ anyone have this problem solution to solve now.

**Comment by philgyford** [comment]
@kaal12 I managed to fix most (but not all) of the errors on mine by reviewing my breadcrumbs HTML and making it more like their examples:

![Screenshot 2019-11-06 at 10 23 52](https://user-images.githubusercontent.com/66670/68290262-8fb3e700-007f-11ea-97fd-597663ec0897.png)

Which I got to from this page https://developers.google.com/search/docs/data-types/breadcrumb

This is the commit where I made the change to my breadcrumbs: https://github.com/philgyford/pepysdiary/commit/baf7c7eb77e4571c69989694bf25e34aef896aa2

I've gone from around 1400 errors to about 40. No idea how to fix those though!
