### ISSUE TITLE
InvalidURL error when new user creates annotation

### ISSUE THREAD

**Issue by jameshibbard** [philgyford/pepysdiary#804]
I got the site up and running and created a superuser as per the instructions in the README.

When I am logged in as superuser and go to a diary entry, I can create an annotation as expected.

However, when I create a new user via the Django's admin panel and log in as that user, creating an annotation results in an InvalidURL error.

---

Steps to reproduce:
- Log into the Django admin panel
- Create a new user (Membership > People > Add Person)
- You are then redirected to an overview of the user you just created
- Set `Is active` to true and enter "ALREADY_ACTIVATED" into the `Activation Key` field
- Hit _Save_ and you are redirected to an overview of users
- Log into the site as the new test user
- Go to a diary entry (e.g.: http://www.pepysdiary.test:8000/diary/1661/10/09/)
- Enter something into the annotation text area
- Hit _Preview your annotation_
- Hit _Post it_
- Observe an `InvalidURL` error (`InvalidURL at /annotations/post/`)
- Go back to the diary entry (e.g.: http://www.pepysdiary.test:8000/diary/1661/10/09/)
- Observe that the annotation was created

Full error message:

```
InvalidURL at /annotations/post/
URL has an invalid label.

Request Method: POST
Request URL: http://www.pepysdiary.test:8000/annotations/post/
Django Version: 5.0.7
Exception Type: InvalidURL
Exception Value: URL has an invalid label.
Exception Location: /usr/local/lib/python3.10/site-packages/requests/models.py, line 456, in prepare_url
Raised during: django_comments.views.comments.post_comment
Python Executable: /usr/local/bin/python
Python Version: 3.10.15
Python Path: ['/code',  '/usr/local/lib/python310.zip', '/usr/local/lib/python3.10', '/usr/local/lib/python3.10/lib-dynload', '/usr/local/lib/python3.10/site-packages']
Server time: Mon, 23 Sep 2024 12:25:03 +0000
```

The reason for this happening seems to be the following check in `spamchecker.py`.

```py
if not hasattr(settings, "PEPYS_AKISMET_API_KEY"):
    # If it's not set we can't test.
    return False
```

When running in dev (with `DEBUG="True"`) `PEPYS_AKISMET_API_KEY` is set to an empty string (even if it is omitted from `.env`, an empty string is its default value). This means that `if not hasattr(settings, "PEPYS_AKISMET_API_KEY")` evaluates to `False`.

Changing the check to:

```py
if not getattr(settings, "PEPYS_AKISMET_API_KEY", ""):
```

Should make things work as expected.

Am I doing it wrong (very possible) or would you like a PR with this change?

**Comment by philgyford** [comment]
Well spotted, that sounds like a good fix, thanks! I'll make the change, probably quickest!
